---
    - name: Download Java
      command: "wget -q -O {{ java_archive }} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ java_download_url }} creates={{ java_archive }}"   
      
    - name: Unpack Archive
      command: "tar -zxf {{ java_archive }} -C {{ download_dir }} creates={{ java_name }}"	  
      
    - name: Fix Ownership
      file:
        state: directory
        path: "{{ java_name }}"
        owner: root
        group: root
        recurse: yes	  
      
    - name: Making java available
      file:
        path: "/usr/bin/java"
        src: "{{ java_name }}/bin/java"
        state: link
        force: yes
      
    - name: Removing java setup file
      file: 
        path: "{{ java_archive }}"
        state: absent
